package engine

import sg "../sokol-odin/sokol/gfx"
import sgl "../sokol-odin/sokol/gl"

// Sokol functions and types

Bindings :: sg.Bindings
Pass :: sg.Pass
Pass_Action :: sg.Pass_Action
Pipeline :: sg.Pipeline
Pipeline_Desc :: sg.Pipeline_Desc
Range :: sg.Range
Color :: sg.Color
Image :: sg.Image
Pixel_Format :: sg.Pixel_Format
sg_setup :: sg.setup
sg_shutdown :: sg.shutdown
sg_isvalid :: sg.isvalid
sg_reset_state_cache :: sg.reset_state_cache
sg_push_debug_group :: sg.push_debug_group
sg_pop_debug_group :: sg.pop_debug_group
sg_add_commit_listener :: sg.add_commit_listener
sg_remove_commit_listener :: sg.remove_commit_listener
sg_make_buffer :: sg.make_buffer
sg_make_image :: sg.make_image
sg_make_sampler :: sg.make_sampler
sg_make_shader :: sg.make_shader
sg_make_pipeline :: sg.make_pipeline
sg_make_pass :: sg.make_pass
sg_destroy_buffer :: sg.destroy_buffer
sg_destroy_image :: sg.destroy_image
sg_destroy_sampler :: sg.destroy_sampler
sg_destroy_shader :: sg.destroy_shader
sg_destroy_pipeline :: sg.destroy_pipeline
sg_destroy_pass :: sg.destroy_pass
sg_update_buffer :: sg.update_buffer
sg_update_image :: sg.update_image
sg_append_buffer :: sg.append_buffer
sg_query_buffer_overflow :: sg.query_buffer_overflow
sg_query_buffer_will_overflow :: sg.query_buffer_will_overflow
sg_begin_default_pass :: sg.begin_default_pass
sg_begin_default_passf :: sg.begin_default_passf
sg_begin_pass :: sg.begin_pass
sg_apply_viewport :: sg.apply_viewport
sg_apply_viewportf :: sg.apply_viewportf
sg_apply_scissor_rect :: sg.apply_scissor_rect
sg_apply_scissor_rectf :: sg.apply_scissor_rectf
sg_apply_pipeline :: sg.apply_pipeline
sg_apply_bindings :: sg.apply_bindings
sg_apply_uniforms :: sg.apply_uniforms
sg_draw :: sg.draw
sg_end_pass :: sg.end_pass
sg_commit :: sg.commit
sg_query_desc :: sg.query_desc
sg_query_backend :: sg.query_backend
sg_query_features :: sg.query_features
sg_query_limits :: sg.query_limits
sg_query_pixelformat :: sg.query_pixelformat
sg_query_buffer_state :: sg.query_buffer_state
sg_query_image_state :: sg.query_image_state
sg_query_sampler_state :: sg.query_sampler_state
sg_query_shader_state :: sg.query_shader_state
sg_query_pipeline_state :: sg.query_pipeline_state
sg_query_pass_state :: sg.query_pass_state
sg_query_buffer_info :: sg.query_buffer_info
sg_query_image_info :: sg.query_image_info
sg_query_sampler_info :: sg.query_sampler_info
sg_query_shader_info :: sg.query_shader_info
sg_query_pipeline_info :: sg.query_pipeline_info
sg_query_pass_info :: sg.query_pass_info
sg_query_buffer_desc :: sg.query_buffer_desc
sg_query_image_desc :: sg.query_image_desc
sg_query_sampler_desc :: sg.query_sampler_desc
sg_query_shader_desc :: sg.query_shader_desc
sg_query_pipeline_desc :: sg.query_pipeline_desc
sg_query_pass_desc :: sg.query_pass_desc
sg_query_buffer_defaults :: sg.query_buffer_defaults
sg_query_image_defaults :: sg.query_image_defaults
sg_query_sampler_defaults :: sg.query_sampler_defaults
sg_query_shader_defaults :: sg.query_shader_defaults
sg_query_pipeline_defaults :: sg.query_pipeline_defaults
sg_query_pass_defaults :: sg.query_pass_defaults
sg_alloc_buffer :: sg.alloc_buffer
sg_alloc_image :: sg.alloc_image
sg_alloc_sampler :: sg.alloc_sampler
sg_alloc_shader :: sg.alloc_shader
sg_alloc_pipeline :: sg.alloc_pipeline
sg_alloc_pass :: sg.alloc_pass
sg_dealloc_buffer :: sg.dealloc_buffer
sg_dealloc_image :: sg.dealloc_image
sg_dealloc_sampler :: sg.dealloc_sampler
sg_dealloc_shader :: sg.dealloc_shader
sg_dealloc_pipeline :: sg.dealloc_pipeline
sg_dealloc_pass :: sg.dealloc_pass
sg_init_buffer :: sg.init_buffer
sg_init_image :: sg.init_image
sg_init_sampler :: sg.init_sampler
sg_init_shader :: sg.init_shader
sg_init_pipeline :: sg.init_pipeline
sg_init_pass :: sg.init_pass
sg_uninit_buffer :: sg.uninit_buffer
sg_uninit_image :: sg.uninit_image
sg_uninit_sampler :: sg.uninit_sampler
sg_uninit_shader :: sg.uninit_shader
sg_uninit_pipeline :: sg.uninit_pipeline
sg_uninit_pass :: sg.uninit_pass
sg_fail_buffer :: sg.fail_buffer
sg_fail_image :: sg.fail_image
sg_fail_sampler :: sg.fail_sampler
sg_fail_shader :: sg.fail_shader
sg_fail_pipeline :: sg.fail_pipeline
sg_fail_pass :: sg.fail_pass
sg_enable_frame_stats :: sg.enable_frame_stats
sg_disable_frame_stats :: sg.disable_frame_stats
sg_frame_stats_enabled :: sg.frame_stats_enabled
sg_query_frame_stats :: sg.query_frame_stats
sg_setup_context :: sg.setup_context
sg_activate_context :: sg.activate_context
sg_discard_context :: sg.discard_context
sg_d3d11_device :: sg.d3d11_device
sg_d3d11_device_context :: sg.d3d11_device_context
sg_d3d11_query_buffer_info :: sg.d3d11_query_buffer_info
sg_d3d11_query_image_info :: sg.d3d11_query_image_info
sg_d3d11_query_sampler_info :: sg.d3d11_query_sampler_info
sg_d3d11_query_shader_info :: sg.d3d11_query_shader_info
sg_d3d11_query_pipeline_info :: sg.d3d11_query_pipeline_info
sg_d3d11_query_pass_info :: sg.d3d11_query_pass_info
sg_mtl_device :: sg.mtl_device
sg_mtl_render_command_encoder :: sg.mtl_render_command_encoder
sg_mtl_query_buffer_info :: sg.mtl_query_buffer_info
sg_mtl_query_image_info :: sg.mtl_query_image_info
sg_mtl_query_sampler_info :: sg.mtl_query_sampler_info
sg_mtl_query_shader_info :: sg.mtl_query_shader_info
sg_mtl_query_pipeline_info :: sg.mtl_query_pipeline_info
sg_wgpu_device :: sg.wgpu_device
sg_wgpu_queue :: sg.wgpu_queue
sg_wgpu_command_encoder :: sg.wgpu_command_encoder
sg_wgpu_render_pass_encoder :: sg.wgpu_render_pass_encoder
sg_wgpu_query_buffer_info :: sg.wgpu_query_buffer_info
sg_wgpu_query_image_info :: sg.wgpu_query_image_info
sg_wgpu_query_sampler_info :: sg.wgpu_query_sampler_info
sg_wgpu_query_shader_info :: sg.wgpu_query_shader_info
sg_wgpu_query_pipeline_info :: sg.wgpu_query_pipeline_info
sg_wgpu_query_pass_info :: sg.wgpu_query_pass_info
sg_gl_query_buffer_info :: sg.gl_query_buffer_info
sg_gl_query_image_info :: sg.gl_query_image_info
sg_gl_query_sampler_info :: sg.gl_query_sampler_info
sg_gl_query_shader_info :: sg.gl_query_shader_info
sg_gl_query_pass_info :: sg.gl_query_pass_info

sgl_Context_Desc :: sgl.Context_Desc
sgl_setup :: sgl.setup
sgl_shutdown :: sgl.shutdown
sgl_rad :: sgl.rad
sgl_deg :: sgl.deg
sgl_error :: sgl.error
sgl_context_error :: sgl.context_error
sgl_make_context :: sgl.make_context
sgl_destroy_context :: sgl.destroy_context
sgl_set_context :: sgl.set_context
sgl_get_context :: sgl.get_context
sgl_default_context :: sgl.default_context
sgl_draw :: sgl.draw
sgl_context_draw :: sgl.context_draw
sgl_draw_layer :: sgl.draw_layer
sgl_context_draw_layer :: sgl.context_draw_layer
sgl_make_pipeline :: sgl.make_pipeline
sgl_context_make_pipeline :: sgl.context_make_pipeline
sgl_destroy_pipeline :: sgl.destroy_pipeline
sgl_defaults :: sgl.defaults
sgl_viewport :: sgl.viewport
sgl_viewportf :: sgl.viewportf
sgl_scissor_rect :: sgl.scissor_rect
sgl_scissor_rectf :: sgl.scissor_rectf
sgl_enable_texture :: sgl.enable_texture
sgl_disable_texture :: sgl.disable_texture
sgl_texture :: sgl.texture
sgl_layer :: sgl.layer
sgl_load_default_pipeline :: sgl.load_default_pipeline
sgl_load_pipeline :: sgl.load_pipeline
sgl_push_pipeline :: sgl.push_pipeline
sgl_pop_pipeline :: sgl.pop_pipeline
sgl_matrix_mode_modelview :: sgl.matrix_mode_modelview
sgl_matrix_mode_projection :: sgl.matrix_mode_projection
sgl_matrix_mode_texture :: sgl.matrix_mode_texture
sgl_load_identity :: sgl.load_identity
sgl_load_matrix :: sgl.load_matrix
sgl_load_transpose_matrix :: sgl.load_transpose_matrix
sgl_mult_matrix :: sgl.mult_matrix
sgl_mult_transpose_matrix :: sgl.mult_transpose_matrix
sgl_rotate :: sgl.rotate
sgl_scale :: sgl.scale
sgl_translate :: sgl.translate
sgl_frustum :: sgl.frustum
sgl_ortho :: sgl.ortho
sgl_perspective :: sgl.perspective
sgl_lookat :: sgl.lookat
sgl_push_matrix :: sgl.push_matrix
sgl_pop_matrix :: sgl.pop_matrix
sgl_t2f :: sgl.t2f
sgl_c3f :: sgl.c3f
sgl_c4f :: sgl.c4f
sgl_c3b :: sgl.c3b
sgl_c4b :: sgl.c4b
sgl_c1i :: sgl.c1i
sgl_point_size :: sgl.point_size
sgl_begin_points :: sgl.begin_points
sgl_begin_lines :: sgl.begin_lines
sgl_begin_line_strip :: sgl.begin_line_strip
sgl_begin_triangles :: sgl.begin_triangles
sgl_begin_triangle_strip :: sgl.begin_triangle_strip
sgl_begin_quads :: sgl.begin_quads
sgl_v2f :: sgl.v2f
sgl_v3f :: sgl.v3f
sgl_v2f_t2f :: sgl.v2f_t2f
sgl_v3f_t2f :: sgl.v3f_t2f
sgl_v2f_c3f :: sgl.v2f_c3f
sgl_v2f_c3b :: sgl.v2f_c3b
sgl_v2f_c4f :: sgl.v2f_c4f
sgl_v2f_c4b :: sgl.v2f_c4b
sgl_v2f_c1i :: sgl.v2f_c1i
sgl_v3f_c3f :: sgl.v3f_c3f
sgl_v3f_c3b :: sgl.v3f_c3b
sgl_v3f_c4f :: sgl.v3f_c4f
sgl_v3f_c4b :: sgl.v3f_c4b
sgl_v3f_c1i :: sgl.v3f_c1i
sgl_v2f_t2f_c3f :: sgl.v2f_t2f_c3f
sgl_v2f_t2f_c3b :: sgl.v2f_t2f_c3b
sgl_v2f_t2f_c4f :: sgl.v2f_t2f_c4f
sgl_v2f_t2f_c4b :: sgl.v2f_t2f_c4b
sgl_v2f_t2f_c1i :: sgl.v2f_t2f_c1i
sgl_v3f_t2f_c3f :: sgl.v3f_t2f_c3f
sgl_v3f_t2f_c3b :: sgl.v3f_t2f_c3b
sgl_v3f_t2f_c4f :: sgl.v3f_t2f_c4f
sgl_v3f_t2f_c4b :: sgl.v3f_t2f_c4b
sgl_v3f_t2f_c1i :: sgl.v3f_t2f_c1i
sgl_end :: sgl.end
